### ISSUE TITLE
the error about env.reset()

### ISSUE THREAD

**Issue by jayyoung0802** [ahjwang/messenger-emma#7]
![image](https://github.com/ahjwang/messenger-emma/assets/42484691/9456df9b-144e-4a8c-8cea-30150f437170)
How to solve it?

**Comment by jayyoung0802** [comment]
I got it with gym==0.21,  setuptools==65.5.0

**Comment by artpli** [comment]
@jayyoung0802 Hi, I encountered the same issue. Have you solved it? And could you please tell me your solution? Thank you very much!

**Comment by artpli** [comment]
I downgraded the gym version to 0.22.0 and it works now.
