### ISSUE TITLE
What is the difference between these three emma_s2_1.pth, emma_s2_2.pth, emma_s2_3.pth?

### ISSUE THREAD

**Issue by jayyoung0802** [ahjwang/messenger-emma#8]
Hi, what is the difference between these three emma_s2_1.pth, emma_s2_2.pth, emma_s2_3.pth ?
test emma_s2_1.pth on msgr-train-v2  Win Rate: 0.930 (93 / 100)
test emma_s2_2.pth on msgr-train-v2  Win Rate: 0.970 (97 / 100)
test emma_s2_3.pth on msgr-train-v2  Win Rate: 0.950 (95 / 100)

**Comment by ahjwang** [comment]
Hello, these three state dicts were from the same EMMA model trained using three different seeds. Hope that helps!
